name: Update Wakatime Stats

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Wakatime data
        run: |
          python assets/fetch.py  

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Wakatime stats"
          branch: main  # Replace with your branch name
